hypertrace/hypertrace-bom

- .github/workflows/publish.yml
- build.gradle.kts
- gradle/libs.versions.toml
- hypertrace-bom/build.gradle.kts
- hypertrace-version-catalog/build.gradle.kts
- owasp-suppressions.xml
- settings.gradle.kts
Adding a published version catalog. Also fix publishing.
> feat: version catalog

- gradle/libs.versions.toml
Update service framework to latest.
> chore: update service framework

- gradle/libs.versions.toml
- hypertrace-bom/build.gradle.kts
- owasp-suppressions.xml
- test-consumer/build.gradle.kts
Added declaration for doc store metrics
> refactor: add doc store metrics

- gradle/libs.versions.toml
Update kafka bom version to pull in dep update
> chore: update kafka bom version

- gradle/libs.versions.toml
Update kafka framework version
> refactor: update kafka framework version

- gradle/libs.versions.toml
- owasp-suppressions.xml
Update service framework, kafka, doc store.
> chore: update versions

- gradle/libs.versions.toml
Update framework libs for http rapid reset fix
> chore: update framework libs

- gradle/libs.versions.toml
- hypertrace-bom/build.gradle.kts
- test-consumer/build.gradle.kts
Add more dependencies needed as usage is shared across more services
> refactor: add more dependencies

- gradle/libs.versions.toml
- hypertrace-bom/build.gradle.kts
- owasp-suppressions.xml
- test-consumer/build.gradle.kts
> chore: add gql deps

- owasp-suppressions.xml
Update expirations for FPs, remove unused.
> chore: update suppressions

- gradle/libs.versions.toml
- owasp-suppressions.xml
Update grpc util and suppression expiration
> chore: update grpc utils version

- gradle/libs.versions.toml
This PR upgrades the codestyle plugin version
> chore: upgrade codestyle plugin version

- gradle/libs.versions.toml
> chore: update config service

- owasp-suppressions.xml
> chore: update suppression expiration

- gradle/libs.versions.toml
- owasp-suppressions.xml
Update GQL version due to CVE. Remove local suppressions as they're now centrally managed.
> chore: update gql version and remove local suppressions

- gradle/libs.versions.toml
> chore: upgrade document-store and service-framework

- gradle/libs.versions.toml
> chore: update document-store and service-framework version

- .github/workflows/pr-build.yml
- gradle/libs.versions.toml
- test-consumer/build.gradle.kts
Due to vuln in protobuf, upgrade
> chore: update protobuf version and add extra verification check

- gradle/libs.versions.toml
> chore: update service-framework version

- gradle/libs.versions.toml
- test-consumer/build.gradle.kts
> Add new service framework to bom

- gradle/libs.versions.toml
> Update document store version

- gradle/libs.versions.toml
Update netty due to some new vuln disclosures
> chore: update netty
